name: telexchat_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_otp_text_field: ^1.5.1+1
  flutter_floating_bottom_bar: ^1.3.0
  flutter_bloc: ^9.1.1
  http: ^1.4.0
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.0
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/src/fonts/
    - lib/src/assets/env/.env
    - lib/src/assets/images/ic_app.jpg

  fonts:
    - family: Google Sans
      fonts:
        - asset: lib/src/fonts/GoogleSans-Regular.ttf
        - asset: lib/src/fonts/GoogleSans-Italic.ttf
          style: italic
        - asset: lib/src/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: lib/src/fonts/GoogleSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/src/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: lib/src/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic

flutter_native_splash:
  color: "#ffffff" 
  image: lib/src/assets/images/ic_app.jpg 
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
